/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrainingRouteImport } from './routes/training'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PlannerRouteImport } from './routes/planner'
import { Route as NutritionRouteImport } from './routes/nutrition'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as RacesRouteRouteImport } from './routes/races/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RacesIndexRouteImport } from './routes/races/index'
import { Route as RacesNewRouteImport } from './routes/races_.new'
import { Route as RacesMapRouteImport } from './routes/races/map'
import { Route as RacesCalendarRouteImport } from './routes/races/calendar'
import { Route as RacesRaceIdRouteImport } from './routes/races/$raceId'

const TrainingRoute = TrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerRoute = PlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const NutritionRoute = NutritionRouteImport.update({
  id: '/nutrition',
  path: '/nutrition',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const RacesRouteRoute = RacesRouteRouteImport.update({
  id: '/races',
  path: '/races',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RacesIndexRoute = RacesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RacesRouteRoute,
} as any)
const RacesNewRoute = RacesNewRouteImport.update({
  id: '/races_/new',
  path: '/races/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RacesMapRoute = RacesMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => RacesRouteRoute,
} as any)
const RacesCalendarRoute = RacesCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => RacesRouteRoute,
} as any)
const RacesRaceIdRoute = RacesRaceIdRouteImport.update({
  id: '/$raceId',
  path: '/$raceId',
  getParentRoute: () => RacesRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/races': typeof RacesRouteRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/nutrition': typeof NutritionRoute
  '/planner': typeof PlannerRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/training': typeof TrainingRoute
  '/races/$raceId': typeof RacesRaceIdRoute
  '/races/calendar': typeof RacesCalendarRoute
  '/races/map': typeof RacesMapRoute
  '/races/new': typeof RacesNewRoute
  '/races/': typeof RacesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/nutrition': typeof NutritionRoute
  '/planner': typeof PlannerRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/training': typeof TrainingRoute
  '/races/$raceId': typeof RacesRaceIdRoute
  '/races/calendar': typeof RacesCalendarRoute
  '/races/map': typeof RacesMapRoute
  '/races/new': typeof RacesNewRoute
  '/races': typeof RacesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/races': typeof RacesRouteRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/nutrition': typeof NutritionRoute
  '/planner': typeof PlannerRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/training': typeof TrainingRoute
  '/races/$raceId': typeof RacesRaceIdRoute
  '/races/calendar': typeof RacesCalendarRoute
  '/races/map': typeof RacesMapRoute
  '/races_/new': typeof RacesNewRoute
  '/races/': typeof RacesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/races'
    | '/dashboard'
    | '/nutrition'
    | '/planner'
    | '/settings'
    | '/stats'
    | '/training'
    | '/races/$raceId'
    | '/races/calendar'
    | '/races/map'
    | '/races/new'
    | '/races/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/nutrition'
    | '/planner'
    | '/settings'
    | '/stats'
    | '/training'
    | '/races/$raceId'
    | '/races/calendar'
    | '/races/map'
    | '/races/new'
    | '/races'
  id:
    | '__root__'
    | '/'
    | '/races'
    | '/dashboard'
    | '/nutrition'
    | '/planner'
    | '/settings'
    | '/stats'
    | '/training'
    | '/races/$raceId'
    | '/races/calendar'
    | '/races/map'
    | '/races_/new'
    | '/races/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RacesRouteRoute: typeof RacesRouteRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  NutritionRoute: typeof NutritionRoute
  PlannerRoute: typeof PlannerRoute
  SettingsRoute: typeof SettingsRoute
  StatsRoute: typeof StatsRoute
  TrainingRoute: typeof TrainingRoute
  RacesNewRoute: typeof RacesNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/training': {
      id: '/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner': {
      id: '/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof PlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutrition': {
      id: '/nutrition'
      path: '/nutrition'
      fullPath: '/nutrition'
      preLoaderRoute: typeof NutritionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/races': {
      id: '/races'
      path: '/races'
      fullPath: '/races'
      preLoaderRoute: typeof RacesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/races/': {
      id: '/races/'
      path: '/'
      fullPath: '/races/'
      preLoaderRoute: typeof RacesIndexRouteImport
      parentRoute: typeof RacesRouteRoute
    }
    '/races_/new': {
      id: '/races_/new'
      path: '/races/new'
      fullPath: '/races/new'
      preLoaderRoute: typeof RacesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/races/map': {
      id: '/races/map'
      path: '/map'
      fullPath: '/races/map'
      preLoaderRoute: typeof RacesMapRouteImport
      parentRoute: typeof RacesRouteRoute
    }
    '/races/calendar': {
      id: '/races/calendar'
      path: '/calendar'
      fullPath: '/races/calendar'
      preLoaderRoute: typeof RacesCalendarRouteImport
      parentRoute: typeof RacesRouteRoute
    }
    '/races/$raceId': {
      id: '/races/$raceId'
      path: '/$raceId'
      fullPath: '/races/$raceId'
      preLoaderRoute: typeof RacesRaceIdRouteImport
      parentRoute: typeof RacesRouteRoute
    }
  }
}

interface RacesRouteRouteChildren {
  RacesRaceIdRoute: typeof RacesRaceIdRoute
  RacesCalendarRoute: typeof RacesCalendarRoute
  RacesMapRoute: typeof RacesMapRoute
  RacesIndexRoute: typeof RacesIndexRoute
}

const RacesRouteRouteChildren: RacesRouteRouteChildren = {
  RacesRaceIdRoute: RacesRaceIdRoute,
  RacesCalendarRoute: RacesCalendarRoute,
  RacesMapRoute: RacesMapRoute,
  RacesIndexRoute: RacesIndexRoute,
}

const RacesRouteRouteWithChildren = RacesRouteRoute._addFileChildren(
  RacesRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RacesRouteRoute: RacesRouteRouteWithChildren,
  DashboardRoute: DashboardRoute,
  NutritionRoute: NutritionRoute,
  PlannerRoute: PlannerRoute,
  SettingsRoute: SettingsRoute,
  StatsRoute: StatsRoute,
  TrainingRoute: TrainingRoute,
  RacesNewRoute: RacesNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
